### ISSUE TITLE
Write Sphinx documentation using Markdown via MyST

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/PyRenew#231]
> 2. Do we want to keep using rst? [I Sphinx supports markdown](https://www.sphinx-doc.org/en/master/usage/markdown.html) (see [here](https://myst-parser.readthedocs.io/en/latest/) also). Maybe, a hybrid between the two would be a solution?

If you feel strongly that this is the better way to go, please open an issue and describe the "hybrid" solution a bit more. If you are on the fence, I think we can just continue with the current workflow and keep focused on higher-priority tasks.

_Originally posted by @damonbayer in https://github.com/CDCgov/multisignal-epi-inference/issues/224#issuecomment-2200413117_

**Comment by dylanhmorris** [comment]
I semi-duplicated this in #235. Will close that one.

**Comment by dylanhmorris** [comment]
## The parameters
We're set on having `.qmd` for literate programming for the moment, and unless/until there's closer Quarto integration for Sphinx, those docs will always need to be rendered to something (`.md`, `.rst`, etc) before being handed off to Sphinx. 

## My preference: use `.md` rather than `.rst`
I slightly favor `.qmd` -> `.md` and the rest of the docs written in regular `.md`, as that comes closest to a single unified coding style. 

## Status quo (`.rst`) would also be fine
I'm also happy to stick with the status quo `.qmd` -> `.rst` and everything else in `.rst` if others prefer that.

## Question
@gvegayon: by "hybrid" did you mean a mix of (non-Quarto) `.md` and `.rst`? If so, what do you see as the potential benefits?

**Comment by dylanhmorris** [comment]
Tagging @CDCgov/multisignal-epi-inference-devs for visibility.

**Comment by damonbayer** [comment]
Agree with all of what @dylanhmorris said above.

**Comment by dylanhmorris** [comment]
I have now tried out Markdown-based sphinx doc sources via [`MyST-parser`](https://myst-parser.readthedocs.io/en/latest/intro.html) in another project. I like it and would support moving to it here.

**Comment by dylanhmorris** [comment]
Another reason to use MyST: https://github.com/CDCgov/multisignal-epi-inference/pull/330#issuecomment-2251477606

We should also investigate ways of taking advantage of [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) etc in tutorial links

**Comment by dylanhmorris** [comment]
Given enthusiasm from @damonbayer and me, I'm going to resolve this in favor of switching over to Markdown via MyST and rename the issue accordingly.
