### ISSUE TITLE
Demonstrate day of the week effect in Time handling in pyrenew tutorial

### ISSUE THREAD

**Issue by damonbayer** [CDCgov/PyRenew#304]
> > The current conflict includes the deleted component on the day-of-the-week effects in #281. This PR fixes it; should I resolve the conflict by including the previously deleted effect?
> 
> Could we demonstrate it in the "Time handling in pyrenew" tutorial instead?
>
> -- @damonbayer 

Surely, but I would like to do that in the next PR then. I think this would be a good opportunity to make use of the ~~`TimeArray`~~ `SampledValue` attributes, for which we would need to: (a) encode time in the observed data, which we are not doing right now, and (b) refactor the implementation of the latent hospitalizations module so it would pass that information to the day-of-the-week effect.

(sorry I added and deleted this comment)

_Originally posted by @gvegayon in https://github.com/CDCgov/multisignal-epi-inference/issues/262#issuecomment-2243838659_

**Comment by gvegayon** [comment]
This issue should be connected to #40 and #185. A few questions that need to be addressed:

1. Should we implement this using the `ObservedData` class that, like the `SampledValues` class, is optionally time-aware?
2. How should we deal with time when simulating data? Will we allow the users to pass only a time vector to consider those timestamps when sampling from the model? As a note, we would have to me time-aware for forecasting (the predictive method).
3. I think this touches on #19. Since we will start passing multiple datasets (which is the ultimate goal of the model), how should the model handle these? Are we passing multiple datasets via the `obs` argument? Should we have multiple `obs` arguments?

These are my current thoughts

1. I think so. The `ObservedData` class could simply be an array of length $T$ with an optional attribute named `time` either `None` or an integer of length $T$. We could use some of the fancy time arrays in [Rockpol](https://synsense.gitlab.io/rockpool/basics/time_series.html#Working-with-time-series-data).
2. In other projects, when the data-generating process is based on covariates (of which time could be one), I have seen (and implemented) frameworks in which the sampling function will take in covariates to simulate the data. 
3. Since the sampling method is model-defined, I think we should have multiple observations when needed, e.g, `obs_admissions` and `obs_wastewater`.

ATT @CDCgov/multisignal-epi-inference-devs

**Comment by damonbayer** [comment]
Great questions, @gvegayon! My first reaction is that this should probably be split into several issues/PRs:

**First, we should get the fix in the "For later" section of https://github.com/CDCgov/multisignal-epi-inference/pull/262 into the repo ASAP.**

Now, replying to your points in order:
1. I think that `ObservedData` class should mimic the `SampledValue` class and have some idea of a `t_start` and `t_unit`, but these would probably be specified in human units. There should be methods for converting this to/from a dataframe.
2. I think we again rely on ideas of `t_start` and `t_unit`, so that forecasting does not rely on additional covariates.
3. I think I agree with your response to this point, but I'm not sure I understand the problem.

**Comment by gvegayon** [comment]
Regarding your other points:

1. Yes, we could build something similar, but in that case, we would require the `ObservedData` class to be pre-processed. Do we want that? I would say we probably do. This takes me to another point: We should probably have a tutorial using pyrenew with raw data, i.e., have a pre-processing step before feeding it into the model.
2. But `t_start` and `t_unit` are currently considered relative to the observed data. So how do we do it if we want to start simulating from, say, Wednesday in a model that features day-of-the-week effects?
3. Not much of a problem, but just thinking ahead to ensure we are all on the same page. So, we don't want a single `ObservedData` that contains, say, lists of arrays, but rather one `ObservedData` for each signal.

About #262, I think I will proceed as follows:

1. Create an RV in which we pre-specify the first day of the week in what will be the observed dataset. This avoids the need to retrieve such information during run-time, which would require passing `ObservedData` instead of an array as we currently do.
2. This cannot be implemented via `t_start`, as `t_start` adds padding forward or backward relative to the first observation.
3. The bottom line is that the implementation would be very similar to what we currently have with `PeriodicEffect`.
